### ISSUE TITLE
img-src is generated with 127.0.0.1

### ISSUE THREAD

**Issue by fleaz** [HaschekSolutions/PictShare-Docker#6]
Hi,
i'm not sure if this is a Docker problem or a general problem with PictShare.
But the page which shows the image after uploading, generates the image url with "http://127.0.0.1" at the beginning.
This throws obviously a 404 when PictShare is running behind an nginx on a server.

As an example, a generated link show `http://127.0.0.1:5443/o8f922hoo1.png` but the corrrect URL should be `https://pictshare.mydomain.de/o8f922hoo1.png`

Best regards, 
Felix

**Comment by geek-at** [comment]
Which parameters did you use to start the container?

**Comment by fleaz** [comment]
I wrote a docker-compose file. But I only defined a volume and a custom port
```
pictshare:
  image: hascheksolutions/pictshare
  ports:
    - "5443:80"
  volumes:
    - "/srv/docker/pictshare:/usr/share/nginx/html/upload"

  restart: always
```
